export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';

export const HOME_SCREEN = 'HOME_SCREEN';
export const ABOUT_SCREEN = 'ABOUT_SCREEN';
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN';
export const SOCIAL_SCREEN = 'SOCIAL_SCREEN';

export const FORUM_SCREEN = 'FORUM_SCREEN';
export const POST_SCREEN = 'POST_SCREEN';
export const NEW_THREAD_SCREEN = 'NEW_THREAD_SCREEN';

export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const ACHIEVEMENTS_SCREEN = 'ACHIEVEMENTS_SCREEN';

export const LEADERBOARD_SCREEN = 'LEADERBOARD_SCREEN';

export const MAP_SEARCH_SCREEN = 'MAP_SEARCH_SCREEN';
export const MAP_BUILDER_SCREEN = 'MAP_BUILDER_SCREEN';

export const REPORTS_SCREEN = 'REPORTS_SCREEN';

export const GAME_SCREEN = 'GAME_SCREEN';