name: CI/CD Pipeline

# Runs on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install client and server dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install
          cd ..

      - name: Build
        run: |
          cd client
          npm run build

      - name: Run server tests
        run: |
          cd server
          npm test

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to hosting provider
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
